apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: fitness-pvc
  namespace: l-ns
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "8Gi"
  # selector:
  #   matchLabels:
  #     app: "fitness" 
