apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fitness-chart.fullname" . }}-fitness-tracker-app
  labels:
  {{- include "fitness-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.fitnessTrackerApp.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.fitnessTrackerApp.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.fitnessTrackerApp.strategy.rollingUpdate.maxUnavailable
        }}
    type: {{ .Values.fitnessTrackerApp.strategy.type | quote }}
  selector:
    matchLabels:
      app: fitness-tracker-app
    {{- include "fitness-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: fitness-tracker-app
      {{- include "fitness-chart.selectorLabels" . | nindent 8 }}
      annotations:
        ad.datadoghq.com/fitness-tracker-app.logs: |-
          [{"source":"nodejs","service":"fitness-tracker-service"},
           {"source":"nodejs","service":"fitness-tracker-app"}]
    spec:
      containers:
      - env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "fitness-chart.fullname" . }}-fitness-configmap
        image: {{ .Values.fitnessTrackerApp.fitnessTrackerApp.image.repository }}:{{ .Values.fitnessTrackerApp.fitnessTrackerApp.image.tag
          | default .Chart.AppVersion }}
        name: fitness-tracker-app
        ports:
        - containerPort: 5000
        resources: {}
      nodeSelector: {{- toYaml .Values.fitnessTrackerApp.nodeSelector | nindent 8 }}
      serviceAccountName: {{ include "fitness-chart.serviceAccountName" . }}
      tolerations: {{- toYaml .Values.fitnessTrackerApp.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.fitnessTrackerApp.topologySpreadConstraints
        | nindent 8 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fitness-chart.fullname" . }}-mongodb
  labels:
  {{- include "fitness-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mongodb.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.mongodb.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.mongodb.strategy.rollingUpdate.maxUnavailable }}
    type: {{ .Values.mongodb.strategy.type | quote }}
  selector:
    matchLabels:
      app: mongodb
    {{- include "fitness-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mongodb
      {{- include "fitness-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mongodb.mongodb.image.repository }}:{{ .Values.mongodb.mongodb.image.tag
          | default .Chart.AppVersion }}
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {{- toYaml .Values.mongodb.mongodb.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-storage
      nodeSelector: {{- toYaml .Values.mongodb.nodeSelector | nindent 8 }}
      serviceAccountName: {{ include "fitness-chart.serviceAccountName" . }}
      tolerations: {{- toYaml .Values.mongodb.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.mongodb.topologySpreadConstraints |
        nindent 8 }}
      volumes:
      - emptyDir:
          sizeLimit: 500Mi
        name: mongodb-storage
