apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fitness-chart.fullname" . }}-fitness-pvc
  labels:
  {{- include "fitness-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.fitnessPvc.storageRequest | quote }}
