apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-service
  labels:
  {{- include "fitness-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fitnessTrackerService.type }}
  selector:
    app: fitness-tracker-app
    {{- include "fitness-chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.fitnessTrackerService.ports | toYaml | nindent 2 }}
