apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fitness-chart.fullname" . }}-fitness-configmap
  labels:
  {{- include "fitness-chart.labels" . | nindent 4 }}
data:
  DD_ENV: {{ .Values.fitnessConfigmap.ddEnv | quote }}
  DD_SERVICE: {{ .Values.fitnessConfigmap.ddService | quote }}
  DD_TRACE_AGENT_PORT: {{ .Values.fitnessConfigmap.ddTraceAgentPort | quote }}
  DD_VERSION: {{ .Values.fitnessConfigmap.ddVersion | quote }}
  HOST: {{ .Values.fitnessConfigmap.host | quote }}
  MONGODB_URI: {{ .Values.fitnessConfigmap.mongodbUri | quote }}
  NODE_ENV: {{ .Values.fitnessConfigmap.nodeEnv | quote }}
  PORT: {{ .Values.fitnessConfigmap.port | quote }}
