apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "fitness-chart.fullname" . }}-mongo-pv
  labels:
    app: fitness
  {{- include "fitness-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /data/my-storage
    server: 10.0.1.169
  persistentVolumeReclaimPolicy: Retain
